### ISSUE TITLE
Gists response object is missing files' contents keys

### ISSUE THREAD

**Issue by hamin** [owainhunt/UAGithubEngine#23]
When I retrieve gists, the files object should contain a contents key/attribute which is the raw text content of the gist. This seems to be missing from all Gists api calls. I can't figure out where exactly the allowed attributes are specified in the library for api requests for gists. Here is a sample response i get for a returned gist

``` objective-c
{
    comments = 0;
    "created_at" = "2012-02-26T17:27:10Z";
    description = "";
    files =     {
        "window_location_to_object.js" =         {
            filename = "window_location_to_object.js";
            language = JavaScript;
            "raw_url" = "https://gist.github.com/raw/07524bc8b3861b2750a6/261a3a16d431334c1309efd84a4fbe031a895861/window_location_to_object.js";
            size = 265;
            type = "application/javascript";
        };
    };
    "git_pull_url" = "git://gist.github.com/07524bc8b3861b2750a6.git";
    "git_push_url" = "git@gist.github.com:07524bc8b3861b2750a6.git";
    "html_url" = "https://gist.github.com/07524bc8b3861b2750a6";
    id = 07524bc8b3861b2750a6;
    public = 0;
    "updated_at" = "2012-02-26T17:27:10Z";
    url = "https://api.github.com/gists/07524bc8b3861b2750a6";
    user =     {
        "avatar_url" = "https://secure.gravatar.com/avatar/684e59a0e53725d2a8291318a42e7ee4?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-140.png";
        "gravatar_id" = 684e59a0e53725d2a8291318a42e7ee4;
        id = 28212;
        login = hamin;
        url = "https://api.github.com/users/hamin";
    };
}
```

If you click on through to the api request https://api.github.com/gists/07524bc8b3861b2750a6 you can see that github is indeed returning the raw contents of each file.

Please advise.

**Comment by owainhunt** [comment]
Fixed [here](https://github.com/owainhunt/UAGithubEngine/commit/3de808fd2c97e49e3ba977bf9bfe09d172bd159e).

**Comment by hamin** [comment]
That fixes the file contents being returned for those methods, but the gistsWithCompletion method still isn't returning the file contents in the JSON response.

``` objective-c
UAGithubEngine *engine = [[UAGithubEngine alloc] initWithUsername:@"hamin" password:@"something" withReachability:YES];

NSArray *gistArray = [engine gistsWithCompletion:^(id obj){return obj; }];
```

I haven't tested but I'm assuming that the following methods won't be returning the file contents of the gist either: publicGistsWithCompletion and starredGistsWithCompletion.

Please advise.

**Comment by hamin** [comment]
@owainhunt so I just realized that the api call for a user's gists doesn't actually return file contents, gistsForCompletion is returning the correct JSON response from Github, I guess I was assuming that the api call would return file contents too, but it doesn't. I guess I have to make api calls for each gist returned in order to retrieve file contents. So yeah, your wrapper is doing the right thing: https://api.github.com/users/hamin/gists
